services:
  backend-auth:
    build: .
    ports:
    - 10000:10000

  debug-auth:
    command: dlv debug --headless --listen=:2345 --api-version=2 --accept-multiclient cmd/authentication/main.go
    build:
      dockerfile: debug.Dockerfile
    ports:
    - 2345:2345
    - 10000:10000
    restart: always
    volumes:
    - .:/src
